language: node_js
before_deploy: git config --global user.email publish@travis.github && git config --global user.name "Travis"
deploy:
  - edge: true
    skip_cleanup: true
    provider: script
    before_script: 
      - npm install
      - npm install --global gulp-cli
    script: gulp deploy
    on:
      branch: development
