language: node_js
before_deploy: 
  - git config --global user.email publish@travis.github && git config --global user.name "Travis"
  - npm install
  - npm install --global gulp-cli
deploy:
  github_token: e78b7b5c86d986c0c30ab143c9dda953750f0633
  skip_cleanup: true
  script: gulp deploy
  on:
    branch: development
branches:
  only:
    - development